server:
  port: 8084
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: funding-service
  profiles:
    active: dev

  batch:
    job:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# Outbox 패턴 설정
outbox:
  max-retries: 3

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.125.94.196:8761/eureka/


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
